/**
 * Prompt-string builders for the AI extraction pipeline.
 *
 * Extracted from travelAI.ts (over the 2,000-line cap). Pure functions that
 * assemble the extraction guidance and the JSON-repair guidance sent to the
 * model. No dependencies — a clean leaf. Imported back by travelAI.ts.
 */

export function buildProposalRepairGuide(rawText: string): string {
  return [
    "Convert the following model output into valid JSON only.",
    "Return exactly one JSON object with this schema:",
    "{",
    '  "summary": "short summary",',
    '  "needs_confirmation": true,',
    '  "important_reason": "reason",',
    '  "conflicts": [],',
    '  "conflict_items": [{ "text": "...", "severity": "info|warning|blocker", "type": "optional" }],',
    '  "actions": [',
    '    { "action": "upsert|patch|cancel", "trip_id": "", "match": { "operator_name": "", "route_name": "" }, "fields": {} }',
    "  ]",
    "}",
    "Do not add markdown fences or explanation text.",
    "",
    "Model output to repair:",
    rawText,
  ].join("\n");
}

export function buildProposalGuide(condensedTrips: unknown): string {
  return [
    "Та travel operations data assistant байна.",
    "Доорх мэдээллээс trips өгөгдлийн санд хийх өөрчлөлтийг тодорхойлж, ЗӨВХӨН JSON буцаа.",
    "Тайлбар текст, markdown, ```код```-ийн хашилт БҮҮ нэм.",
    "",
    "JSON schema:",
    "{",
    '  "summary": "товч дүгнэлт (монголоор)",',
    '  "needs_confirmation": true/false,',
    '  "important_reason": "яагаад баталгаажуулах ёстой эсэх",',
    '  "conflicts": [],',
    '  "conflict_items": [',
    '    { "text": "хүний ойлгох тайлбар (монголоор)", "severity": "info|warning|blocker", "type": "optional_type_tag" }',
    "  ],",
    '  "actions": [',
    "    {",
    '      "action": "upsert|patch|cancel",',
    '      "trip_id": "trip id (optional)",',
    '      "match": { "operator_name": "...", "route_name": "..." },',
    '      "fields": {',
    '        "category": "", "operator_name": "", "route_name": "", "duration_text": "",',
    '        "adult_price": 0, "child_price": 0, "currency": "MNT|CNY",',
    '        "departure_dates": ["..."], "seats_total": null, "seats_left": null,',
    '        "has_food": true, "status": "active|cancelled|sold_out|draft",',
    '        "notes": "", "source_description": "",',
    '        "extra": {',
    '          "tour_title": "canonical product title", "route": "actual travel path",',
    '          "duration_days": null, "duration_nights": null,',
    '          "recurring_schedule": null, "departure_date_groups": [],',
    '          "infant_prices": [], "single_room_supplements": [], "foreign_currency_fees": [],',
    '          "transport": [], "included_items": [], "excluded_items": [], "itinerary_days": [],',
    '          "source_file_name": "", "original_title_text": "",',
    '          "extraction_confidence": { "operator": "high|medium|low", "title": "high|medium|low", "dates": "high|medium|low", "prices": "high|medium|low", "duration": "high|medium|low" }',
    "        }",
    "      }",
    "    }",
    "  ]",
    "}",
    "",
    'conflict_items severity дүрэм (ХАМГИЙН ЧУХАЛ):',
    '- "blocker": зөвхөн жинхэнэ зөрчил — ижил аялал+ижил огноо+ижил аялагчдын төрөл+тайлбаргүй өөр үнэ. Blocker байвал needs_confirmation=true болгоно.',
    '- "warning": анхаарал хэрэгтэй боловч хадгалахыг зогсоохгүй. Жишээ: тодорхойгүй талбар, нэмэлт зардал.',
    '- "info": ердийн мэдээлэл. Хадгалахыг зогсоохгүй, асуухгүй. Жишээ: дүрмийн мэдэгдэл.',
    'conflict_items дэх "type" (заавал биш, тогтмол ашиглавал):',
    '  adult_child_normal | date_based_pricing | optional_addon | duplicate_route | true_price_conflict | ocr_suspect | meal_exception',
    "",
    "Баталгаажуулалт заавал true болгох нөхцөл:",
    "- Маршрут цуцлах (status=cancelled),",
    "- Үнийн том өөрчлөлт,",
    "- Суудал 0 болгох эсвэл sold_out болгох,",
    "- Нэгээс олон маршрут таарах магадлалтай үед,",
    "- Файлаас уншсан өгөгдөл бүрхэг/эргэлзээтэй үед.",
    "",
    "Дүрэм:",
    "- Одоо байгаа маршрутыг шинэчлэхдээ trip_id эсвэл match (operator_name+route_name) ашигла.",
    "- Шинэ маршрут бол action='upsert', trip_id хоосон үлдээ.",
    "- Мэдээлэл байхгүй талбарыг БҮҮ таа — fields-ээс орхи.",
    "- Үнийн валют: 'юань'/'yuan' → CNY, 'төгрөг'/'сая' эсвэл 6+ оронтой тоо → MNT.",
    "- Хэрэв ямар ч өөрчлөлт хийх шаардлагагүй бол actions хоосон массив байг.",
    "",
    "Талбар таних заавар (админ ярианы хэлээр асууж магадгүй):",
    "- 'Огноо', 'хэзээ', 'гарах өдөр', 'цаг' → departure_dates. 'өдөр бүр', 'daily', 'пүрэв гараг бүр' зэрэг давтагдах хуваарь ХҮЧИНТЭЙ departure_dates утга — огноо алга гэж бүү тооц.",
    "- Тодорхой цагийн мэдээлэл (ж: '09:00 цагт') departure_dates-д эсвэл notes-д бич.",
    "- 'Газар', 'байршил', 'хаашаа', 'чиглэл', 'маршрут' → route_name (шаардлагатай бол notes-д дэлгэрэнгүй).",
    "- 'Суудал', 'хүн', 'багтаамж' → seats_total/seats_left. 'Суудал дүүрсэн/дууссан' → status=sold_out.",
    "- Зөвхөн нэг талбар өөрчлөхөд action='patch' ашиглаж, бусад талбарыг БҮҮ хүр.",
    "- Хэрэглэгч шинэ аялал нэмэхгүй, зөвхөн одоо байгаа аяллын нэрийг нөх гэж хэлбэл ЗӨВХӨН action='patch' ашигла. Одоо байгаа нэргүй аяллын trip_id-г заавал сонго; action='upsert' бүү ашигла.",
    "- Нэрсийг дарааллаар нөхөх хүсэлтэд source-ийн эхний нэрийг created_order=1 нэргүй аялалтай, дараагийн нэрийг created_order=2-той тус тус тааруул.",
    "- Админ 'үүнийг'/'энэ аяллыг' гэж тодорхойгүй заавал, аль аялал болохыг trips жагсаалтаас тааруул. Олон аялал таарвал эсвэл огт тодорхойгүй бол needs_confirmation=true болгон аль аяллыг асуу.",
    "",
    "=== TRAVEL AGENCY DOMAIN RULES FOR conflict_items ===",
    "",
    "ХЭВИЙН зүйл — ОГТХОН Ч зөрчил биш (conflict_items дотор дурдахгүй):",
    "  • Том хүний үнэ > хүүхдийн үнэ > нярайн үнэ (эсвэл тэнцүү) — аялалын агентлагийн ердийн дүрэм",
    "  • Нэг аяллын олон гарах огноо — олон хуваарьтай байх нь хэвийн",
    "  • Сар, улирал, эсвэл гарах огноогоор үнэ өөр — ердийн сезоны үнэ (departure_dates+notes-д бич, blocker болгохгүй)",
    "  • Нэмэлт төлбөр CNY/юань-аар (шинжилгээ, хувийн зардал, single room, нэмэлт үзвэр) — notes-д хадгал",
    "  • Хоол зарим өдрөөр хэрэглэгчийн зардлаар (чөлөөт өдрүүд) — has_food=true, notes-д тайлбарла",
    "  • 'Пүрэв гараг бүр', 'өдөр бүр', 'сар бүр' зэрэг давтагдах хуваарь — хүчинтэй departure_dates",
    "",
    "INFO (severity='info') — мэдээлэл, хадгалахыг зогсоохгүй, асуухгүй:",
    "  • Аялалын нэрийг нарийвчлах боломжтой боловч одоогийн нэр бас зөв",
    "  • Single room нэмэлт нь суурь үнийн гаднах зардал гэдгийг тодруулах",
    "",
    "WARNING (severity='warning') — анхаарал хэрэгтэй, хадгалахыг ЗОГСООХГҮЙ, зөвхөн yellow box:",
    "  • Нэр маш ижил хоёр аялал давхцаж магадгүй — нягтлаарай",
    "  • Тоон утга буруу унших эрсдэлтэй мэт (ж: 2,6360,000 — OCR алдаа байж болох)",
    "  • Verification pass-ийн зөрүү",
    "",
    "BLOCKER (severity='blocker') — жинхэнэ зөрчил, needs_confirmation=true БОЛГОХ, менежерт АСУУХ:",
    "  • Ижил аялал + ижил огноо + ижил аялагчдын төрөл + тайлбаргүй өөр үнэ",
    "  • Хүүхдийн үнэ > том хүний үнэ (урвуу — буруу мэт)",
    "  • Маршрутын нэр (route_name) огт байхгүй бол blocker болго; operator_name байхгүй бол 'UUDAM TRAVEL AGENCY' гэж бич — blocker биш",
    "  • Цуцлах (status=cancelled) үйлдэл — менежер баталгаажуулах ёстой",
    "",
    "TEXT FORMAT дүрэм:",
    "- Энгийн, ойлгомжтой ярианы хэлээр бич. Аялалын менежертэй ярьж байгаа мэт.",
    "- Техник нэр томьёо, талбарын нэр, ID (trip_id, route_name, seed-33 г.м.) БҮҮ дурд.",
    "- Аяллын нэрийг ХАШИЛТАНД бич (ж: \"Жэжү арлын аялал 2026\").",
    "- Аль зүйл тодорхойгүй болон яг утгуудыг нь энгийнээр дурд.",
    "- \"Нэг аяллын...\", \"зарим аялал...\" гэх ерөнхий бичлэг хориотой.",
    "- Гарах огноог departure_dates-д оруулсан бол conflicts-д 'огноо тодорхойгүй' гэж БҮҮ бич.",
    "- Сайн жишээ: { \"text\": \"\\\"Хөх хотын шинжилгээтэй аялал\\\"-ыг шинэ аялал болгон нэмэх үү, эсвэл одоо байгааг шинэчлэх үү?\", \"severity\": \"blocker\", \"type\": \"duplicate_route\" }",
    "- Муу жишээ (БҮҮ): { \"text\": \"...-д том хүний үнэ хүүхдийн үнэ-өөс өндөр байна.\", \"severity\": \"blocker\" } — ЭНЭ НЬ ХЭВИЙН, blocker болгохгүй.",
    "",
    `Одоогийн trips (JSON): ${JSON.stringify(condensedTrips)}`,
  ].join("\n");
}
