import {
  normalizeTripOffers, resolveTripOffer, resolveTripOfferFareCard,
  type CanonicalTripOffer, type OfferAvailability, type OfferFare, type ResolvedTripOffer, type TripOfferResult, type TripOfferSelection,
} from "./tripOffers";
import type { TravelTrip } from "./travelTypes";

export type WebsiteDeparture = {
  start: string;
  end: string;
  label: string;
  price: number | null;
  childPrice: number | null;
  infantPrice: number | null;
  status: "OPEN" | "SOLD_OUT" | "PAUSED" | "CANCELLED";
  seatsLeft: number | null;
};
export type WebsiteDepartureDate = Pick<WebsiteDeparture, "start" | "end" | "label">;
export type WebsiteOfferEntry = {
  selection: TripOfferSelection;
  result: TripOfferResult;
  fareCard: TripOfferResult;
};

function exactAmount(fare: OfferFare | undefined): number | null {
  return fare?.kind === "exact" || fare?.kind === "free" ? fare.amount : null;
}

/**
 * A trip can have more than one child band (for example 2-5 and 6-11). The
 * offer resolver deliberately refuses to pretend those are one fare, but the
 * website's legacy `childPrice` column still needs the explicitly-published
 * headline fare for date lists and admin views. The complete tier list stays
 * in `passenger_prices`; this is only its backwards-compatible projection.
 */
function scalarAmount(source: Record<string, unknown> | undefined, kind: "adult" | "child" | "infant") {
  const value = source?.[`${kind}_price`];
  return typeof value === "number" && Number.isFinite(value) && value >= 0 ? value : null;
}

function displayAmount(
  offer: ResolvedTripOffer,
  kind: "adult" | "child" | "infant",
  source: Record<string, unknown> | undefined,
) {
  const resolved = offer.prices[kind];
  const exact = exactAmount(resolved);
  if (exact !== null) return exact;
  // Only restore a scalar when the resolver withheld it because several age
  // bands need a passenger-age choice. A range, missing fare, or a catalog
  // conflict must stay non-exact and therefore quote-only.
  return resolved?.kind === "unknown" && resolved.reason === "passenger_age_required"
    ? scalarAmount(source, kind)
    : null;
}

function displayOffer(entry: WebsiteOfferEntry): ResolvedTripOffer | null {
  if (entry.fareCard.status !== "ready") return null;
  const availability = entry.result.status === "unavailable" ? entry.result.availability : undefined;
  return availability ? { ...entry.fareCard.offer, availability } : entry.fareCard.offer;
}

function confirmedOpen(availability: OfferAvailability): boolean {
  return availability.status === "open";
}

function websiteStatus(status: string, seatsLeft: number | null): WebsiteDeparture["status"] {
  if (status === "sold_out") return "SOLD_OUT";
  if (status === "cancelled" || status === "departed") return "CANCELLED";
  // A missing seat count means staff have not published a count, not that the
  // departure is closed. Keep it selectable unless somebody explicitly pauses
  // or closes that date.
  if ((status === "open" || status === "unknown") && seatsLeft !== 0) return "OPEN";
  return "PAUSED";
}

/** Undo only an unchanged pause generated by our unknown-seat projection. */
export function websiteAvailabilityForResync(
  departure: { date: string; status: string; seatsLeft: number | null }, previous: unknown,
) {
  const object = (value: unknown): Record<string, unknown> => value && typeof value === "object" && !Array.isArray(value)
    ? value as Record<string, unknown> : {};
  const metadata = object(previous);
  const projected = Array.isArray(metadata.departures) ? metadata.departures.map(object)
    .find(row => typeof row.start === "string" && row.start.slice(0, 10) === departure.date) : undefined;
  if (departure.status !== "PAUSED" || departure.seatsLeft !== null
    || projected?.status !== "PAUSED" || projected.seatsLeft !== null) return departure;
  const entries = Array.isArray(metadata.entries) ? metadata.entries.map(object) : [];
  const availability = entries.filter(entry => object(entry.selection).date === departure.date)
    .map(entry => object(object(object(entry.fareCard).offer).availability))
    .find(row => ["unknown", "open"].includes(String(row.status)) && row.seatsLeft === null);
  return availability ? { ...departure, status: String(availability.status).toUpperCase() } : departure;
}

function fareRow(offer: ResolvedTripOffer, sourceRows: Map<string, Record<string, unknown>>) {
  const source = offer.sourceOfferIds.map(id => sourceRows.get(id)).find(Boolean);
  const adult = displayAmount(offer, "adult", source);
  const sourceWithoutDimensions = { ...(source || {}) };
  delete sourceWithoutDimensions.hotel;
  delete sourceWithoutDimensions.hotel_id;
  delete sourceWithoutDimensions.package_id;
  return {
    ...sourceWithoutDimensions,
    ...(typeof source?.single_price === "number" ? { single_price: source.single_price } : {}),
    id: offer.id,
    label: offer.date,
    dates: [offer.date], display_dates: [offer.date], date_keys: [offer.date],
    ...(offer.hotel ? { hotel: offer.hotel } : {}),
    ...(offer.hotelId ? { hotel_id: offer.hotelId } : {}),
    ...(offer.packageId ? { package_id: offer.packageId } : {}),
    adult_price: adult,
    adult_price_range: offer.prices.adult?.kind === "range" ? { min: offer.prices.adult.min, max: offer.prices.adult.max } : null,
    child_price: displayAmount(offer, "child", source), infant_price: displayAmount(offer, "infant", source),
    passenger_prices: offer.fares.filter(fare => fare.kind !== "adult").map(fare => ({
      label: `${fare.kind === "infant" ? "Нярай" : "Хүүхэд"}${fare.ageRange ? ` ${fare.ageRange}` : ""}`,
      age_range: fare.ageRange || "", price: exactAmount(fare.fare), currency: fare.currency,
      ...(fare.fare.kind === "free" ? { note: "Үнэгүй" } : {}),
      ...(fare.fare.kind === "range" ? { price_range: { min: fare.fare.min, max: fare.fare.max } } : {}),
    })),
    currency: offer.currency,
    availability: offer.availability,
  };
}

function sourceRowsById(trip: TravelTrip, offers: CanonicalTripOffer[]) {
  const values = (value: unknown): Record<string, unknown>[] => Array.isArray(value)
    ? value.filter((item): item is Record<string, unknown> => Boolean(item && typeof item === "object" && !Array.isArray(item) && Object.keys(item).length)) : [];
  const groups = {
    base: [], legacy: values(trip.extra.departure_date_groups), price_group: values(trip.extra.price_groups),
    discount: [...values(trip.extra.discounts), ...values(trip.extra.discount_groups)],
  };
  const indexes = { base: 0, legacy: 0, price_group: 0, discount: 0 };
  return new Map(offers.filter(offer => offer.source !== "base").map(offer =>
    [offer.id, groups[offer.source][indexes[offer.source]++]]));
}

function selectionsForDate(offers: CanonicalTripOffer[], date: string): TripOfferSelection[] {
  const candidates = offers.filter(offer => offer.source !== "base" && offer.source !== "discount"
    && (!offer.dateScoped || offer.dates.includes(date)));
  const hotels = [...new Map(candidates.filter(offer => offer.hotel || offer.hotelId)
    .map(offer => [offer.hotelId || offer.hotel, offer])).values()];
  const selections = (hotels.length ? hotels : [null]).flatMap(hotel => {
    const matching = candidates.filter(offer => !offer.hotel && !offer.hotelId
      || hotel && (hotel.hotelId ? offer.hotelId === hotel.hotelId : offer.hotel?.toLowerCase() === hotel.hotel?.toLowerCase()));
    const packages = [...new Set(matching.map(offer => offer.packageId).filter((id): id is string => Boolean(id)))];
    return (packages.length ? packages : [null]).map(packageId => ({
      date,
      ...(hotel?.hotelId ? { hotelId: hotel.hotelId } : hotel?.hotel ? { hotel: hotel.hotel } : {}),
      ...(packageId ? { packageId } : {}),
    }));
  });
  return [...new Map(selections.map(selection => [JSON.stringify(selection), selection])).values()];
}

/** Existing website columns are a lossy display projection; metadata retains every scoped fare. */
export function websiteTripPayload(trip: TravelTrip, schedule: WebsiteDepartureDate[], now = new Date()) {
  const datedTrip = { ...trip, departure_dates: schedule.map(departure => departure.start.slice(0, 10)) };
  const sources = normalizeTripOffers(datedTrip, now);
  const sourceRows = sourceRowsById(trip, sources);
  const entries: WebsiteOfferEntry[] = schedule.flatMap(departure => {
    const date = departure.start.slice(0, 10);
    return selectionsForDate(sources, date).map(selection => ({
      selection, result: resolveTripOffer(datedTrip, selection, now),
      fareCard: resolveTripOfferFareCard(datedTrip, selection, now),
    }));
  });
  const departures: WebsiteDeparture[] = schedule.map(departure => {
    const date = departure.start.slice(0, 10);
    const scoped = entries.filter(entry => entry.selection.date === date);
    const offers = scoped.flatMap(entry => {
      const offer = displayOffer(entry);
      if (!offer) return [];
      const source = offer.sourceOfferIds.map(id => sourceRows.get(id)).find(Boolean);
      return [{ offer, source }];
    });
    const bookable = offers.filter(({ offer }) => confirmedOpen(offer.availability));
    const choices = bookable.length ? bookable : offers;
    const primary = [...choices].sort((left, right) =>
      (displayAmount(left.offer, "adult", left.source) ?? Infinity) - (displayAmount(right.offer, "adult", right.source) ?? Infinity))[0];
    const unavailable = scoped.find(entry => entry.result.status === "unavailable");
    const availability = primary?.offer.availability
      || (unavailable?.result.status === "unavailable" ? unavailable.result.availability : undefined)
      || { status: "unavailable", seatsLeft: null };
    return {
      ...departure,
      price: primary ? displayAmount(primary.offer, "adult", primary.source) : null,
      childPrice: primary ? displayAmount(primary.offer, "child", primary.source) : null,
      infantPrice: primary ? displayAmount(primary.offer, "infant", primary.source) : null,
      status: primary && displayAmount(primary.offer, "adult", primary.source) === null && confirmedOpen(availability)
        ? "PAUSED" : websiteStatus(availability.status, availability.seatsLeft), seatsLeft: availability.seatsLeft,
    };
  });
  const primaryDate = departures.find(departure => departure.status === "OPEN" && departure.price !== null)
    || departures.find(departure => departure.price !== null);
  const headlineOffers = entries.filter(entry => entry.selection.date === primaryDate?.start.slice(0, 10))
    .map(displayOffer).filter((offer): offer is ResolvedTripOffer => Boolean(offer))
    .filter(offer => exactAmount(offer.prices.adult) === primaryDate?.price);
  const headline = headlineOffers.find(offer => confirmedOpen(offer.availability)) || headlineOffers[0];
  const ageRules = Object.fromEntries((["adult", "child", "infant"] as const).flatMap(kind => {
    const bands = [...new Set(headline?.fares.filter(fare => fare.kind === kind).map(fare => fare.ageRange).filter(Boolean))];
    return bands.length === 1 ? [[kind, bands[0]]] : [];
  }));
  return {
    departures,
    price: primaryDate?.price ?? null,
    childPrice: primaryDate?.childPrice ?? null,
    infantPrice: primaryDate?.infantPrice ?? null,
    ageRules,
    priceGroups: entries.map(displayOffer).filter((offer): offer is ResolvedTripOffer => Boolean(offer))
      .map(offer => fareRow(offer, sourceRows)),
    canonicalOffers: { version: 1, sources, entries, departures },
  };
}
